import {
  FaBehance,
  FaDiscord,
  FaDribbble,
  FaEnvelope,
  FaFacebook,
  FaGlobe,
  FaLink,
  FaLinkedin,
  FaPhone,
  FaPinterest,
  FaStore,
  FaTelegramPlane,
  FaWhatsapp,
  FaYoutube,
} from "react-icons/fa";
import { LuBookOpen, LuBriefcaseBusiness, LuMail, LuMessageCircle, LuMonitorPlay, LuNewspaper, LuStore } from "react-icons/lu";
import {
  RxDiscordLogo,
  RxGithubLogo,
  RxInstagramLogo,
  RxLinkedinLogo,
  RxLink2,
  RxTwitterLogo,
} from "react-icons/rx";
import {
  SiFigma,
  SiBluesky,
  SiBuymeacoffee,
  SiCalendly,
  SiCodepen,
  SiDevdotto,
  SiFrontendmentor,
  SiGmail,
  SiGithub,
  SiGumroad,
  SiHashnode,
  SiKickstarter,
  SiKofi,
  SiLinktree,
  SiLoom,
  SiMastodon,
  SiMedium,
  SiNetlify,
  SiNotion,
  SiPatreon,
  SiShopify,
  SiProducthunt,
  SiReddit,
  SiSpotify,
  SiStackoverflow,
  SiSubstack,
  SiTelegram,
  SiThreads,
  SiTiktok,
  SiTwitch,
  SiUpwork,
  SiVercel,
  SiWhatsapp,
  SiX,
} from "react-icons/si";
import type { IconType } from "react-icons";

export type IconCatalogEntry = {
  id: string;
  label: string;
  category: string;
  tags: string[];
};

const ICON_MAP: Record<string, IconType> = {
  FaBehance,
  FaDiscord,
  FaDribbble,
  FaEnvelope,
  FaFacebook,
  FaGlobe,
  FaLink,
  FaLinkedin,
  FaPhone,
  FaPinterest,
  FaStore,
  FaTelegramPlane,
  FaWhatsapp,
  FaYoutube,
  LuBookOpen,
  LuBriefcaseBusiness,
  LuMail,
  LuMessageCircle,
  LuMonitorPlay,
  LuNewspaper,
  LuStore,
  RxDiscordLogo,
  RxGithubLogo,
  RxInstagramLogo,
  RxLinkedinLogo,
  RxLink2,
  RxTwitterLogo,
  SiFigma,
  SiBluesky,
  SiBuymeacoffee,
  SiCalendly,
  SiCodepen,
  SiDevdotto,
  SiFrontendmentor,
  SiGmail,
  SiGithub,
  SiGumroad,
  SiHashnode,
  SiKickstarter,
  SiKofi,
  SiLinktree,
  SiLoom,
  SiMastodon,
  SiMedium,
  SiNetlify,
  SiNotion,
  SiPatreon,
  SiProducthunt,
  SiReddit,
  SiShopify,
  SiSpotify,
  SiStackoverflow,
  SiSubstack,
  SiTelegram,
  SiThreads,
  SiTiktok,
  SiTwitch,
  SiUpwork,
  SiVercel,
  SiWhatsapp,
  SiX,
};

export const ICON_CATALOG: IconCatalogEntry[] = [
  {
    id: "RxGithubLogo",
    label: "GitHub",
    category: "Developer",
    tags: ["code", "repository", "developer"],
  },
  {
    id: "SiVercel",
    label: "Vercel",
    category: "Developer",
    tags: ["deployment", "hosting", "frontend"],
  },
  {
    id: "SiNetlify",
    label: "Netlify",
    category: "Developer",
    tags: ["deployment", "hosting", "frontend"],
  },
  {
    id: "SiNotion",
    label: "Notion",
    category: "Developer",
    tags: ["workspace", "notes", "docs"],
  },
  {
    id: "SiCodepen",
    label: "CodePen",
    category: "Developer",
    tags: ["frontend", "snippets", "playground"],
  },
  {
    id: "SiStackoverflow",
    label: "Stack Overflow",
    category: "Developer",
    tags: ["questions", "answers", "developer"],
  },
  {
    id: "SiDevdotto",
    label: "DEV Community",
    category: "Developer",
    tags: ["blog", "developer", "articles"],
  },
  {
    id: "SiHashnode",
    label: "Hashnode",
    category: "Developer",
    tags: ["blog", "developer", "articles"],
  },
  {
    id: "SiFrontendmentor",
    label: "Frontend Mentor",
    category: "Developer",
    tags: ["frontend", "challenges", "portfolio"],
  },
  {
    id: "SiFigma",
    label: "Figma",
    category: "Developer",
    tags: ["design", "ui", "ux"],
  },
  {
    id: "SiProducthunt",
    label: "Product Hunt",
    category: "Business",
    tags: ["launch", "startup", "products"],
  },
  {
    id: "SiUpwork",
    label: "Upwork",
    category: "Business",
    tags: ["freelance", "services", "work"],
  },
  {
    id: "LuBriefcaseBusiness",
    label: "Portfolio",
    category: "Business",
    tags: ["business", "services", "profile"],
  },
  {
    id: "FaStore",
    label: "Store",
    category: "Business",
    tags: ["shop", "commerce", "products"],
  },
  {
    id: "LuStore",
    label: "Showcase",
    category: "Business",
    tags: ["catalog", "shop", "products"],
  },
  {
    id: "SiShopify",
    label: "Shopify",
    category: "Business",
    tags: ["store", "commerce", "shop"],
  },
  {
    id: "SiCalendly",
    label: "Calendly",
    category: "Business",
    tags: ["booking", "meeting", "schedule"],
  },
  {
    id: "RxInstagramLogo",
    label: "Instagram",
    category: "Social Media",
    tags: ["social", "photo", "reels"],
  },
  {
    id: "FaFacebook",
    label: "Facebook",
    category: "Social Media",
    tags: ["social", "community"],
  },
  {
    id: "RxTwitterLogo",
    label: "Twitter / X",
    category: "Social Media",
    tags: ["social", "x", "twitter"],
  },
  {
    id: "SiX",
    label: "X",
    category: "Social Media",
    tags: ["social", "twitter", "x"],
  },
  {
    id: "RxLinkedinLogo",
    label: "LinkedIn",
    category: "Social Media",
    tags: ["social", "jobs", "business"],
  },
  {
    id: "FaLinkedin",
    label: "LinkedIn Classic",
    category: "Social Media",
    tags: ["social", "jobs", "business"],
  },
  {
    id: "SiThreads",
    label: "Threads",
    category: "Social Media",
    tags: ["social", "meta"],
  },
  {
    id: "SiTiktok",
    label: "TikTok",
    category: "Social Media",
    tags: ["video", "social", "shorts"],
  },
  {
    id: "SiReddit",
    label: "Reddit",
    category: "Social Media",
    tags: ["community", "forum", "social"],
  },
  {
    id: "FaPinterest",
    label: "Pinterest",
    category: "Social Media",
    tags: ["social", "images", "inspiration"],
  },
  {
    id: "SiBluesky",
    label: "Bluesky",
    category: "Social Media",
    tags: ["social", "microblog", "community"],
  },
  {
    id: "SiMastodon",
    label: "Mastodon",
    category: "Social Media",
    tags: ["social", "fediverse", "community"],
  },
  {
    id: "FaYoutube",
    label: "YouTube",
    category: "Content",
    tags: ["video", "content", "channel"],
  },
  {
    id: "LuMonitorPlay",
    label: "Live Demo",
    category: "Content",
    tags: ["demo", "preview", "presentation"],
  },
  {
    id: "SiMedium",
    label: "Medium",
    category: "Content",
    tags: ["blog", "writing", "articles"],
  },
  {
    id: "SiSubstack",
    label: "Substack",
    category: "Content",
    tags: ["newsletter", "writing", "blog"],
  },
  {
    id: "LuNewspaper",
    label: "Blog",
    category: "Content",
    tags: ["news", "posts", "articles"],
  },
  {
    id: "LuBookOpen",
    label: "Docs",
    category: "Content",
    tags: ["documentation", "guide", "readme"],
  },
  {
    id: "SiLoom",
    label: "Loom",
    category: "Content",
    tags: ["video", "recording", "presentation"],
  },
  {
    id: "RxDiscordLogo",
    label: "Discord",
    category: "Messaging",
    tags: ["community", "chat", "server"],
  },
  {
    id: "FaDiscord",
    label: "Discord Classic",
    category: "Messaging",
    tags: ["community", "chat", "server"],
  },
  {
    id: "SiTelegram",
    label: "Telegram",
    category: "Messaging",
    tags: ["chat", "community", "messaging"],
  },
  {
    id: "FaTelegramPlane",
    label: "Telegram Classic",
    category: "Messaging",
    tags: ["chat", "community", "messaging"],
  },
  {
    id: "FaWhatsapp",
    label: "WhatsApp",
    category: "Messaging",
    tags: ["chat", "phone", "messaging"],
  },
  {
    id: "SiWhatsapp",
    label: "WhatsApp Alt",
    category: "Messaging",
    tags: ["chat", "phone", "messaging"],
  },
  {
    id: "LuMessageCircle",
    label: "Message",
    category: "Messaging",
    tags: ["chat", "message", "contact"],
  },
  {
    id: "FaEnvelope",
    label: "Email",
    category: "Utility",
    tags: ["mail", "contact", "message"],
  },
  {
    id: "LuMail",
    label: "Email Alt",
    category: "Utility",
    tags: ["mail", "contact", "message"],
  },
  {
    id: "SiGmail",
    label: "Gmail",
    category: "Utility",
    tags: ["mail", "google", "contact"],
  },
  {
    id: "FaPhone",
    label: "Phone",
    category: "Utility",
    tags: ["call", "contact", "mobile"],
  },
  {
    id: "FaGlobe",
    label: "Website",
    category: "Utility",
    tags: ["homepage", "site", "web"],
  },
  {
    id: "FaLink",
    label: "Link",
    category: "Utility",
    tags: ["url", "external", "resource"],
  },
  {
    id: "RxLink2",
    label: "Link Alt",
    category: "Utility",
    tags: ["url", "external", "resource"],
  },
  {
    id: "SiSpotify",
    label: "Spotify",
    category: "Creator",
    tags: ["music", "audio", "podcast"],
  },
  {
    id: "FaBehance",
    label: "Behance",
    category: "Creator",
    tags: ["design", "portfolio", "creative"],
  },
  {
    id: "FaDribbble",
    label: "Dribbble",
    category: "Creator",
    tags: ["design", "portfolio", "creative"],
  },
  {
    id: "SiPatreon",
    label: "Patreon",
    category: "Creator",
    tags: ["support", "membership", "creator"],
  },
  {
    id: "SiGumroad",
    label: "Gumroad",
    category: "Creator",
    tags: ["products", "creator", "sales"],
  },
  {
    id: "SiKofi",
    label: "Ko-fi",
    category: "Creator",
    tags: ["support", "donation", "creator"],
  },
  {
    id: "SiBuymeacoffee",
    label: "Buy Me a Coffee",
    category: "Creator",
    tags: ["support", "donation", "creator"],
  },
  {
    id: "SiLinktree",
    label: "Linktree",
    category: "Creator",
    tags: ["profile", "links", "social"],
  },
  {
    id: "SiTwitch",
    label: "Twitch",
    category: "Creator",
    tags: ["stream", "gaming", "live"],
  },
  {
    id: "SiKickstarter",
    label: "Kickstarter",
    category: "Creator",
    tags: ["funding", "launch", "creator"],
  },
  {
    id: "SiGithub",
    label: "GitHub Alt",
    category: "Developer",
    tags: ["code", "repository", "developer"],
  },
];

export const AVAILABLE_ICONS = ICON_CATALOG.map((icon) => icon.id);

export function getIcon(name: string | null): IconType | null {
  if (!name) return null;
  return ICON_MAP[name] ?? null;
}

export function getIconMeta(name: string | null): IconCatalogEntry | null {
  if (!name) return null;
  return ICON_CATALOG.find((icon) => icon.id === name) ?? null;
}

export function isAvailableIcon(name: string | null | undefined): name is string {
  return Boolean(name && ICON_MAP[name]);
}
